Bump bindgen dependency
The previous version was quite old. The dependency on clang-sys would
also prevent depending crates from using a newer version, as Windows
does not allow linking to clang using different clang-sys versions. This
would produce errors such as:

    error: multiple packages link to native library `clang`, but a native library can be linked only once
    package `clang-sys v0.21.2`
        ... which is depended on by `bindgen v0.31.3`
        ... which is depended on by `libffi-sys v0.6.3`
        ... which is depended on by `inko v0.3.0 (C:\projects\inko\vm)`
    links to native library `clang`
    package `clang-sys v0.28.0`
        ... which is depended on by `bindgen v0.49.0`
        ... which is depended on by `wepoll-sys v1.0.2`
        ... which is depended on by `inko v0.3.0 (C:\projects\inko\vm)`
    also links to native library `clang`
    make: *** [Makefile:30: test] Error 101
    make: Leaving directory '/c/projects/inko/vm'